# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true
collections:
  - talks


# edit here to achieve your personal greatness
url: https://drob.net
title: David Roberts
author: David Roberts
description: TECHNOLOGY, TRAVEL, AND OTHER INTERESTING TOPICS
avatar: profile.png
email: hi@drob.net
github: droberts84
twitter: drobtravels
linkedin: droberts10
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
# google_analytics:


# needed for travis-ci build
exclude: [vendor]
